### ISSUE TITLE
Unexpected Token (5:22)

### ISSUE THREAD

**Issue by AbsolofDarkness** [gabrielbull/react-desktop#142] opened 2019-05-21 23:22 UTC
I am not understanding why this is happening. I have copied the code over, and still get this.

**Comment by davej** [comment] 2019-05-22 04:25
Can you please provide steps to reproduce.

**Comment by davej** [comment] 2019-05-31 06:36
Closing because there's no detail to reproduce.

**Closed by davej** 2019-05-31 06:36 UTC
