### ISSUE TITLE
Why not use in Electron

### ISSUE THREAD

**Issue by 173954105** [gabrielbull/react-desktop#127] opened 2018-08-09 08:35 UTC
My code:
`import { Button } from 'react-desktop/macOs';
ReactDOM.render(
    (<Button color="blue" onClick={() => console.log('Clicked!')}>
        Press me!
    </Button>),
    document.getElementById('test')
);`

error:
`Uncaught Error: Element ref was specified as a string (element) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a functional component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://fb.me/react-refs-must-have-owner for more information.
    at invariant (react-dom.development.js:59)
    at coerceRef (react-dom.development.js:12352)
    at reconcileSingleElement (react-dom.development.js:13054)
    at reconcileChildFibers (react-dom.development.js:13109)
    at reconcileChildrenAtExpirationTime (react-dom.development.js:13480)
    at finishClassComponent (react-dom.development.js:13682)
    at updateClassComponent (react-dom.development.js:13625)
    at beginWork (react-dom.development.js:14293)
    at performUnitOfWork (react-dom.development.js:16319)
    at workLoop (react-dom.development.js:16358)`

`The above error occurred in the <Button> component:
    in Button
    in _class
    in _class
    in _class
    in _class
    in _class2

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:14691
`

**Comment by davej** [comment] 2018-08-09 22:52
I could not reproduce this. Please provide a reproducible repository or CodeSandbox. Closing until repro is available.

**Closed by davej** 2018-08-09 22:52 UTC
